# Generated by Django 2.2.5 on 2022-08-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220822_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='county',
            new_name='country',
        ),
    ]
