# Generated by Django 2.2.5 on 2022-08-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20220823_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(help_text='How many bed do you need?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='How many people will be staying?'),
        ),
    ]
